name: bbzcloud_mobil
description: "BBZCloud Mobile - Flutter App für iOS und Android"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # WebView
  flutter_inappwebview: ^6.1.5
  
  # Storage & Database
  sqflite: ^2.4.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  path: ^1.9.0
  
  # Network
  http: ^1.2.2
  url_launcher: ^6.3.1
  android_intent_plus: ^5.1.0
  
  # Navigation
  go_router: ^14.6.2
  
  # Utils
  intl: ^0.20.1
  uuid: ^4.5.1
  crypto: ^3.0.6
  logger: ^2.4.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # File Operations
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.2
  
  # Testing
  mockito: ^5.4.4
  sqflite_common_ffi: ^2.3.0
  
  # Icon Generation
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"
