name: Build Android

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Generate app icons
        run: flutter pub run flutter_launcher_icons
        continue-on-error: false
      
      - name: Commit generated icons
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add android/app/src/main/res/mipmap-*/ || true
          git add ios/Runner/Assets.xcassets/AppIcon.appiconset/ || true
          git diff --quiet && git diff --staged --quiet || \
          (git commit -m "chore: regenerate app icons [skip ci]" && git push) || true
        continue-on-error: true
      
      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings
      
      - name: Run tests
        run: flutter test --reporter expanded
      
      - name: Generate test coverage
        run: flutter test --coverage
        continue-on-error: true
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test/
          retention-days: 30
      
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: coverage/
          retention-days: 30
      
      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons
      
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
      
      - name: Build App Bundle
        run: flutter build appbundle --release --no-tree-shake-icons
      
      - name: Upload App Bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 30
      
      - name: Get version
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Create Release Info
        run: |
          echo "## Build Information" > release-info.txt
          echo "" >> release-info.txt
          echo "- **Version**: ${{ steps.version.outputs.version }}" >> release-info.txt
          echo "- **Branch**: ${{ github.ref_name }}" >> release-info.txt
          echo "- **Commit**: ${{ github.sha }}" >> release-info.txt
          echo "- **Date**: $(date +'%Y-%m-%d %H:%M:%S')" >> release-info.txt
          echo "" >> release-info.txt
          echo "## Download" >> release-info.txt
          echo "" >> release-info.txt
          echo "Download the artifacts from the GitHub Actions run." >> release-info.txt
      
      - name: Upload Release Info
        uses: actions/upload-artifact@v4
        with:
          name: release-info
          path: release-info.txt
          retention-days: 30
